### ISSUE TITLE
Installation unter Fedora

### ISSUE THREAD

**Issue by The-Saint2k** [EinApfelBaum/otr-verwaltung3p#107]
Hallo,
ich nutze das Tool schon lange unter Ubuntu. Nun bin ich auf Fedora umgeschwugen. Leider weiß ich nicht wie ich es hier installieren kann. Könnte mir da jemand ein paar Tips geben.?

**Comment by gCurse** [comment]
Die folgende Liste enthält die zu installierenden Abhängigkeiten (Ubuntu Paketnamen). Du müsstest die entsprechenden Fedora Pakete installieren (die sehr wahrscheinlich andere Namen haben).
OTRV selbst kannst Du dann wie folgt installieren:
`git clone --branch development --single-branch --shallow-since=2020-02-14 https://github.com/EinApfelBaum/otr-verwaltung3p.git`

Das kopiert OTRV in den Ordner "otr-verwaltung3p" im aktuellen Verzeichnis.
Starten kann man es dann im Terminal mit `/<pfad>/<zu>/otr-verwaltung3p/bin/otrverwaltung3p` oder mit `bin/otrverwaltung`, wenn Du das Terminal im Verzeichnis "otr-verwaltung3p" öffnest.

**Comment by gCurse** [comment]
Upps, habe die Liste vergessen.

Die zu installierenden Abhängigkeiten (Ubuntu Paketnamen):
ffmpeg
ffmsindex
gir1.2-gstreamer-1.0
gir1.2-gtk-3.0
gstreamer1.0-gtk3
gstreamer1.0-libav
gstreamer1.0-plugins-bad
gstreamer1.0-plugins-base
gstreamer1.0-plugins-base-apps
gstreamer1.0-plugins-good
gstreamer1.0-plugins-ugly
gstreamer1.0-tools
gstreamer1.0-x
mediainfo
mediainfo-gui
mkvtoolnix
mpv
python3-appdirs
python3-cairo
python3-crypto
python3-gi-cairo
python3-gst-1.0
python3-requests
python3-xdg
git
x264
