### ISSUE TITLE
OTR Verwaltung 3p crashes with UnicodeDecodeError when easydecoder reports errors

### ISSUE THREAD

**Issue by major-mayer** [EinApfelBaum/otr-verwaltung3p#108]
Hi,
I noticed that when you try to decode a otrkey file that was downloaded from a time, when you didn't have premium status, it simply hangs.
In the UI there is no error message presented or whatsoever, which is quite confusing, because it took me a while to find out, that I didn't have Premium back then.
In console i found the following:
```
~ >>> otrverwaltung3p                                                     [130]
otr-verwaltung3p, version 1.0.0b8.post1
Gdk-Message: 23:00:21.641: Window 0x5616f90f85f0 is a temporary window without parent, application will not be able to position it on screen.

(otrverwaltung3p:75369): Gdk-CRITICAL **: 23:00:21.643: gdk_wayland_window_handle_configure_popup: assertion 'impl->transient_for' failed
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/otrverwaltung3p/gui/MainWindow.py", line 890, in _on_toolbutton_clicked
    self.app.perform_action(action, cut_action)
  File "/usr/bin/otrverwaltung3p", line 770, in perform_action
    action.do(chosen_action, filenames, cut_action)
  File "/usr/lib/python3.8/site-packages/otrverwaltung3p/actions/decodeorcut.py", line 82, in do
    if not self.decode(file_conclusions):
  File "/usr/lib/python3.8/site-packages/otrverwaltung3p/actions/decodeorcut.py", line 293, in decode
    errors = process.stderr.readlines()
  File "/usr/lib/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf6 in position 77: invalid start byte
~ >>>                                                                          
```

If the OnlineTvRecoder API returns a error if the decoding request is not valid because of missing premium, it would be nice to present this error message to the user.

**Comment by gCurse** [comment]
Sorry for the late reply.
OTRV tries to report errors but crashes because of a decoding exception.

Can you please post the output of
`/usr/share/otrverwaltung3p/tools/intern-easydecoder -e <your email-address here> -p <your password here> -i <path to otrkey-file which causes the crash>`
__Do not post the command itself! (private data)__

I *think* the following may work:
Close otr-verwaltung3p.
Open "/usr/lib/python3.8/site-packages/otrverwaltung3p/actions/decodeorcut.py" in an editor (root privileges required).
Search for 
`command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, universal_newlines=True,`

and change it to
`command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, errors="replace", universal_newlines=True,`

Save the file an try to decode again.

**Comment by major-mayer** [comment]
Here you go, that's the output of the decoder software:
```
Verifying input ...
Successfully verified input.
Check authorization ...

Error: Ihr Guthaben reicht nicht aus, um diese Sendung zu dekodieren. Sie ben�tigen 5 Cent mehr. Weil: 
-Diese Datei ist �lter als 372 Tage und Sie hatten zur Ausstrahlung keinen Premium-Status (+5 Cent). 

Informationen zu Fehlermeldungen des Dekoders finden Sie hier: http://www.onlinetvrecorder.com/?aktion=decodermessages
```

And indeed changing the line in decodeorcut.py seems to work :+1: :smiley: 
The error is only visible when you click on the  "Geschnittene Dateien anzeigen" (show cutted files) button, i think that can be easily overlooked.
Maybe you could warn the user more visible. But thanks for the quick fix anyway.

**Comment by gCurse** [comment]
Done in eabc7a3
